// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:4d5a0c99-78b4-4dd5-a004-e7bd35a6d275",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_9rTl1kvUX",
    "aws_user_pools_web_client_id": "2t92kjhc044pouvo143kkp2jl0",
    "aws_appsync_graphqlEndpoint": "https://6as54jldhzgpplsjrrpe7vzpgi.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
